from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent
REPO = ROOT.parent.parent
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(REPO / "pce-core" / "src"))
sys.path.insert(0, str(REPO / "agents" / "llm-assistant" / "src"))

from trader_plugins.runtime import TraderRuntime


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="PCE Trader agent CLI")
    sub = parser.add_subparsers(dest="command", required=True)

    replay = sub.add_parser("replay", help="Replay candles from CSV and emit decisions")
    replay.add_argument("--csv", required=True, help="CSV with candles: symbol,timeframe,timestamp,open,high,low,close,volume")

    dataset = sub.add_parser("dataset", help="Dataset build utilities")
    dataset_sub = dataset.add_subparsers(dest="dataset_command", required=True)
    dataset_build = dataset_sub.add_parser("build", help="Build feature dataset from candles")
    dataset_build.add_argument("--candles-csv", required=True)
    dataset_build.add_argument("--out", required=True)
    dataset_build.add_argument("--symbols", required=True, help="comma separated, ex: BTCUSDT,ETHUSDT")
    dataset_build.add_argument("--timeframe", default="1h")

    train = sub.add_parser("train", help="Train model from dataset CSV (preferred) or legacy feature CSV")
    train.add_argument("--dataset", required=False, help="dataset generated by `dataset build`")
    train.add_argument("--csv", required=False, help="legacy alias for dataset")

    model = sub.add_parser("model", help="Model registry operations")
    model_sub = model.add_subparsers(dest="model_command", required=True)
    activate = model_sub.add_parser("activate", help="Set approved model as active")
    activate.add_argument("--version", required=True)

    live = sub.add_parser("live-demo", help="Fetch latest real market data and run one cycle")
    live.add_argument("--output", default="agents/trader/artifacts/live_demo.json", help="Output JSON path")

    ledger = sub.add_parser("ledger", help="Inspect append-only event ledger")
    ledger_sub = ledger.add_subparsers(dest="ledger_command", required=True)
    ledger_tail = ledger_sub.add_parser("tail", help="Show last N events")
    ledger_tail.add_argument("--limit", type=int, default=200)

    ledger_query = ledger_sub.add_parser("query", help="Query events by type/symbol/time")
    ledger_query.add_argument("--type", dest="event_type", default=None)
    ledger_query.add_argument("--symbol", default=None)
    ledger_query.add_argument("--since-ts", default=None)
    ledger_query.add_argument("--limit", type=int, default=50)

    ui = sub.add_parser("ui", help="Run local Trader web UI server")
    ui.add_argument("--host", default="127.0.0.1", help="Bind host (default: 127.0.0.1)")
    ui.add_argument("--port", type=int, default=8787, help="UI port")
    ui.add_argument("--loop-interval", type=float, default=5.0, help="Control-loop interval in seconds")

    return parser


def main() -> int:
    args = build_parser().parse_args()
    runtime = TraderRuntime()

    if args.command == "dataset" and args.dataset_command == "build":
        result = runtime.build_dataset_from_candles(
            candles_csv=Path(args.candles_csv),
            out_path=Path(args.out),
            symbols=[s.strip() for s in str(args.symbols).split(",") if s.strip()],
            timeframe=str(args.timeframe),
        )
        print(json.dumps(result, ensure_ascii=False, indent=2))
        return 0

    if args.command == "replay":
        decisions = runtime.replay_csv(Path(args.csv))
        print(json.dumps({"decisions": decisions}, ensure_ascii=False, indent=2))
        return 0

    if args.command == "train":
        dataset = args.dataset or args.csv
        if not dataset:
            raise SystemExit("--dataset (ou --csv legado) é obrigatório")
        result = runtime.train_from_csv(Path(dataset))
        print(json.dumps(result, ensure_ascii=False, indent=2))
        return 0

    if args.command == "model" and args.model_command == "activate":
        print(json.dumps(runtime.activate_model(args.version), ensure_ascii=False, indent=2))
        return 0

    if args.command == "live-demo":
        result = runtime.live_demo_once()
        out = Path(args.output)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
        print(json.dumps({"output": str(out), "decisions": len(result)}, ensure_ascii=False))
        return 0

    if args.command == "ledger":
        if args.ledger_command == "tail":
            print(json.dumps(runtime.ledger.tail(args.limit), ensure_ascii=False, indent=2))
            return 0
        if args.ledger_command == "query":
            print(
                json.dumps(
                    runtime.ledger.query(
                        event_type=args.event_type,
                        symbol=args.symbol,
                        since_ts=args.since_ts,
                        limit=args.limit,
                    ),
                    ensure_ascii=False,
                    indent=2,
                )
            )
            return 0

    if args.command == "ui":
        import uvicorn
        from ui_server import create_app

        print(f"PCE Observability Console: http://{args.host}:{args.port}")
        uvicorn.run(create_app(loop_interval_s=args.loop_interval), host=args.host, port=args.port)
        return 0

    return 1


if __name__ == "__main__":
    raise SystemExit(main())
